### ISSUE TITLE
`shutil.copy2()` broken in Python 3.12 for Windows

### ISSUE THREAD

**Issue by bzczb** [batonogov/docker-pyinstaller#50]
Python 3.12 uses Windows's `CopyFile2()` function to implement `shutil.copy2()`. [(link)](https://docs.python.org/3/whatsnew/changelog.html#id58) Unfortunately `CopyFile2()` is not implemented in WINE, so any build tools that use `copy2()` will break.

Extremely hacky workaround:

`sed -i 's/if hasattr(_winapi, "CopyFile2"):/if False:/g' /wine/drive_c/Python3/Lib/shutil.py`

Not sure if there's much can be done on this end, other than waiting for WINE to implement `CopyFile2()`, but this Docker image enables such a pleasant CI that I intend to use the hacky workaround.
Nothing breaks in [entrypoint-windows.sh](https://github.com/batonogov/docker-pyinstaller/blob/main/entrypoint-windows.sh), it's only when you have to [build a wheel](https://github.com/pypa/pip/blob/5efa3e83d90b1d64fbf0104d2ba84bef8d7e9648/src/pip/_vendor/pyproject_hooks/_in_process/_in_process.py#L247-L249).

**Comment by batonogov** [comment]
Thank you for your issue! Your answer is very helpful. 

Unfortunately, I cannot suggest a simpler solution to this problem other than waiting for WINE to implement CopyFile2(). However, if you want to continue using Docker and your hacky workaround, this may be a good solution for you. 

Thank you again for your answer!

**Comment by Xenoamor** [comment]
Thanks for the fix @bzczb 
Looks like there's an implementation of CopyFile2 in the works for Wine https://gitlab.winehq.org/wine/wine/-/merge_requests/5020
