### ISSUE TITLE
[Request] Older Glibc

### ISSUE THREAD

**Issue by imxade** [batonogov/docker-pyinstaller#97]
**Is your feature request related to a problem? Please describe.**
- newly built executable doesn't work on ubuntu 20.04

**Describe the solution you'd like**
- Building Linux executables with older Glibc will ensure better compatibility

**Comment by batonogov** [comment]
Hi. Thanks for the issue. 

I see the solution to your problem as follows: make **different tags** for **docker images** in the format: `ubuntu:20.04-python:3.12.4`

This will allow you to get different versions of **glibc** for different builds.

**Comment by batonogov** [comment]
I prepared the necessary changes. Since Python images use Debian, I made versions of Bookworm and Bullseye.

If i run bookworm image:

```sh
docker run \
  --volume "$(pwd)/test/:/src/" \
  ghcr.io/batonogov/pyinstaller-linux:pr-98-slim-bookworm \
  "pyinstaller --onefile main.py" \
  && docker run --rm -it -v "$(pwd)/test/dist:/dist" ubuntu:20.04 /dist/main
```
I see error

```sh
[7] Failed to load Python shared library '/tmp/_MEIVuPauh/libpython3.12.so.1.0': dlopen: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIVuPauh/libpython3.12.so.1.0)
```

But if i tun buulseye image:

```sh
docker run \
  --volume "$(pwd)/test/:/src/" \
  ghcr.io/batonogov/pyinstaller-linux:pr-98-slim-bullseye \
  "pyinstaller --onefile main.py" \
  && docker run --rm -it -v "$(pwd)/test/dist:/dist" ubuntu:20.04 /dist/main
```

My test application working good:

```sh
Response Status Code: 200
```

Now you can use this image for testing, i make changes to the next release.
